### PR TITLE
Modified latin corpora

### PR DESCRIPTION
**Pull request by dev-sabbir**

### CODE REVIEW

**Comment by kylepjohnson** [comment]
Hi, Can you let me know the change you made to this? Also, I will give you write access to this repo.

**Comment by dev-sabbir** [comment]
Sir,
You have mentioned that some files in greek corpora is empty. So I checked both latin and greek repo for empty text files. And found some. So, I re wrote my parser to get data for those empty files also. In short I have populated the empty files in both greek and latin corpora.
Thank you.

**Comment by kylepjohnson** [comment]
Terrific, thank you!

In the future, always give an summary of the changes you made, partially to remind me but also so those in the future can easily review your work.

**Comment by dev-sabbir** [comment]
Ok sir, will do so in future.
Thank you.

**Pull request merged**
